### ISSUE TITLE
test: update submit service gRPC tests for case where request includes invalid flatbuffer type

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hubble#315]
There are two skipped tests in the gRPC SubmitService test:
* https://github.com/farcasterxyz/hub/blob/9a56364caa423e328b9de188020789d858257d06/src/rpc/test/submitService.test.ts#L96
* https://github.com/farcasterxyz/hub/blob/9a56364caa423e328b9de188020789d858257d06/src/rpc/test/submitService.test.ts#L122

These skipped tests should cover the case where a gRPC client sends a request to the submit service with an invalid flatbuffer object. However, the current client implementation of `submitIdRegistryEvent` and `submitNameRegistryEvent` take models as arguments that wrap the underlying flatbuffers. If those flatbuffers are invalid, the models will throw an exception on initialization, so we have to implement a new client in order to test this part of the gRPC server.

**Comment by adaddeo** [comment]
picking this up

**Comment by adaddeo** [comment]
I have the tests setup with a client that doesn't use the model objects. However, to get the expected behavior the service also needs to be updated as currently it attempts to [construct a model](https://github.com/farcasterxyz/hub/blob/main/src/rpc/server/serviceImplementations/submitImplementation.ts#L47) that ends up throwing and the callback is never called.

To move #213 forward, using a pattern for building and validating objects that didn't rely on throw/catch is ideal. I didn't find any examples of this (specifically constructing and validating class based objects without throwing) in other parts of the codebase. I can take a stab at it but I thought I'd check to 1) make sure I'm not missing an established pattern and 2) if one of the core developers had something in mind since there are many ways to skin this cat.

**Comment by pfletcherhill** [comment]
Fixed with protobuf gRPC implementation
