### ISSUE TITLE
fix: Protocol should use a space-efficient serialization format

### ISSUE THREAD

**Issue by kcchu** [farcasterxyz/hubble#430]
**What is the bug?**

Farcaster v2 currently uses FlatBuffers in most protocol messages and RPC. While FlatBuffers is extremely fast to decode, its wire format is indeed bigger than alternatives such as Protobuf. Since hub's storage is a scarce resource in Farcaster, the serialization format chosen for persisted data (such as signed protocol messages) should be as space-efficient as possible.

**How can it be reproduced? (optional)**

I wrote a benchmarking project for Protobuf and FlatBuffers on Go (because Node is too slow for a meaningful benchmark, and Go is a popular choice for implementing decentralized protocols). The test data is a Farcaster's Message.

It shows that the differences in encoding performance is tiny, but the wire format size is substantially larger (+40%).

https://github.com/kcchu/buffer-benchmarks

| Test                              | Protobuf | FlatBuffers | Capnp |
| --------------------------------- | -------- | ----------- | ----- |
| Encode (ns/op)                    | 882.7    | 859.0       | 2541  |
| Decode (ns/op)                    | 1165     | 18.36       | 1726  |
| Wire format size (bytes)          | 299      | 432         | 344   |
| Wire format size, gzipped (bytes) | 323      | 406         | 368   |

**Additional context (optional)**

The bigger wire format of FlatBuffers is mostly due to its use of vtable, field alignments and constant size integers. 

Besides space-efficiency, FlatBuffers have other drawbacks:

  * Security - FlatBuffers's use of vtable could easily lead to security vulnerabilities on memory unsafe languages if the incoming messages were not verified carefully. Some FlatBuffers libraries can verify the vtable, but this would eliminates any advantages on decoding speed. And even if verification is done, DoS may still be possible with maliciously crafted messages containing circular pointers. ([Reference](https://github.com/dvidelabs/flatcc/blob/master/doc/security.md))
  * Fewer support for gRPC+FlatBuffers: While gRPC+FlatBuffers is possible by gRPC specification, there is very scarce open source support for this. With gRPC+Protobuf, server stubs and clients can easily be generated from proto file for many programming languages. With gRPC+FlatBuffers, [server stub and client](https://github.com/farcasterxyz/hub/blob/main/apps/hub/src/rpc/syncDefinitions.ts) have to be written manually.
  * Tedious message construction - Building of FlatBuffers messages is difficult. As a result, extra hand-written code is maintained to [build the messages](https://github.com/farcasterxyz/hub/blob/main/packages/js/src/builders.ts).

**Comment by pfletcherhill** [comment]
Thanks for doing the benchmarking! I'll certainly take a look at that. It's worth noting though that the flatbuffers decode performance was a large part of why we chose it, because it means that hubs can validate and resolve conflicts between encoded messages much faster than they could with a framework that required deserialization.

**Comment by pfletcherhill** [comment]
These are all very good points. We've done a lot more benchmarking over the last couple of days that confirm the benchmarking you already did and are evaluating what it would take to make the switch to protobufs.

**Comment by pfletcherhill** [comment]
For the sake of planning, here's a list of tasks we'd need to do in order to migrate to protobufs.

### Messages and contract events migration

- [ ] Add `@farcaster/protobufs` package with schemas and static code
- [ ] Port message schemas to protobufs (`message.fbs`)
- [ ] Port contract event schemas to protobufs (`id_registry_event.fbs` and `name_registry_event.fbs`)
- [ ] Add factories for protobufs messages and events in `@farcaster/utils`
- [ ] Add verifications for protobufs in `@farcaster/utils`
- [ ] Add signers that use protobufs `SignatureScheme` rather than flatbuffers to `@farcaster/utils`

### Storage engine migration
- [ ] Update stores to use protobuf messages and events
- [ ] Port job-related schemas to protobufs (`job.fbs`)
- [ ] Update jobs to use protobufs
- [ ] Update storage engine to use protobuf messages and events

### gRPC migration
- [ ] Port gRPC schemas to protobufs (`rpc.fbs`)
- [ ] Update gRPC server implementations
- [ ] Update gRPC client implementations

### Eth migration
- [ ] Update Eth events provider to use protobufs

### Gossip and sync migration
- [ ] Port gossip schemas to protobufs (`gossip.fbs`)
- [ ] Update p2p classes and gossip factories to use protobufs
- [ ] Update sync engine to use protobufs
- [ ] Update sync console to use protobufs

### Hub script migration
- [ ] Port hub state schemas to protobufs (`hub_state.fbs`)
- [ ] Update hub executable and cli to use protobufs

**Comment by TimDaub** [comment]
If I can help doing smaller tasks in this epic, I‘m happy to send some PRs.

**Comment by pfletcherhill** [comment]
Closing due to https://github.com/farcasterxyz/hubble/pull/480
