### ISSUE TITLE
bug: builder functions fail validations with "0x00" target hash

### ISSUE THREAD

**Issue by adaddeo** [farcasterxyz/hubble#461]
**What is the bug?**
Builder functions that take a target hash fail validations when the hash starts with `0x00`.

- when a [tsHash is serialized](https://github.com/farcasterxyz/hub/blob/main/packages/js/src/utils.ts#L638-L640) a non-padding byte array is generated
- when a [tsHash is validated](https://github.com/farcasterxyz/hub/blob/main/packages/utils/src/validations.ts#L68-L72) exact length is checked for

**How can it be reproduced? (optional)**
```
const tsHashHex = '0x00' + Factories.TsHashHex.build().substring(4);
const data = await builders.makeReactionRemoveData(
  { type: Factories.ReactionType.build(), target: { fid, tsHash: tsHashHex } },
  { fid, timestamp, network }
);
```
[test case](https://github.com/farcasterxyz/hub/compare/main...adaddeo:hub:builder-tshash-bug#diff-4bf4bdb45b0162af922193b1ad53bb0b5a540e3a1e8ab69ef66131670e3957baR94-R102)

**Additional context (optional)**
Related to #443

**Comment by pfletcherhill** [comment]
This problem should go away with the protobufs implementation in `@farcaster/protoutils` for two reasons...


* **No more timestamp hashes**. We're removing any use of timestamp hashes in the message schemas and replacing it just with hash (relevant for CastId and CastRemoveBody). The hash is long enough to identify a unique cast, and clients don't have to worry about correctly constructing the timestamp hash from a message they want to reference. We're continuing to use timestamp hashes inside the hub to index data, but clients don't need to worry about it.

* **Fixed size byte arrays**. Rather than try to remove padding from all byte arrays with protobufs, we're going to keep byte arrays whatever size they were and validate them against fixed sizes based on the context (i.e. an eth address must be 20 bytes, etc). The biggest reason we were removing padding with flatbuffers was because we represented fid as bytes everywhere that could be as large as 32 bytes. So we could save a lot of space by stripping all padding from fids. However, with protobufs, we're referring to fid just as a number and encoding it as `uint64` in the protobuf, so protobufs can store it efficiently and handle endianness.

**Comment by pfletcherhill** [comment]
Closing due to https://github.com/farcasterxyz/hubble/pull/480
