### ISSUE TITLE
test: automated test to verify event propagation to warpcast api

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#588]
**What is the feature you would like to implement?**

Perform a test to verify that messages generated by one application can propagate to another via the Hubs event service. 

**Why is this feature important?**

Verifying this gives us confidence that message propagation works correctly before we open it up to broader usage. 

**Will the protocol spec need to be updated??**

No

**How should this feature be built? (optional)**

Write out a thorough suite of test cases to test different permutations of events (e.g. cast, reply, signer, signer remove). Once a thorough test suite is established, generate test messages and push them to a mainnet hub inside a docker container and verify that the api responses are what we expect them to be.

**Comment by varunsrin** [comment]
@pfletcherhill mentioned in a conversation that the area most likely to be fragile is the parts where merges from contract events intersect with merges of hub messages. pfh will spend some time writing out test cases, and then @sds or @varunsrin will take a pass as well before moving forward.

**Comment by pfletcherhill** [comment]
Some test cases to consider...

### Remove arrives without an add or before an add
* Applicable for any store except the UserDataStore
* A client creates conflicting add and remove messages and either only submits the remove or submits the remove before the add
* In both cases the hub will emit a single `mergeMessage` event for the remove
* Ensure that the backend can handle removes without corresponding adds (casts, reactions, etc)

### UserDataAdd for fname arrives before corresponding name registry event
* Both the backend and the hub are ingesting events from the NameRegistry contract
* A user buys an fname and assigns the fname to their fid with a UserDataAdd message when the NameRegistry event hits the hub (if they submit it before the event arrives, the hub will reject it because their fid does not own the given fname)
* When the backend receives the UserDataAdd message with the fname, it may not have already ingested the relevant NameRegistry event but it should still assign the fname to the user

### Handle `deletedMessages` field on `mergeMessage`
* When a message is merged and overwrites another message, the hub emits a `mergeMessage` event with the new message and a list of deleted messages
* Ensure that the backend cleans up any state relating to the deleted messages

### Handle `revokeMessage` events
* The hub emits `revokeMessage` events when the signer of the message is removed
* It also emits a `revokeMessage` for a UserDataAdd of type `USER_DATA_TYPE_FNAME` when the fname being assigned is transferred to a different address
* Ensure the backend handles both of these situations

### SignerAdd arrives before corresponding ID registry event
* A user may register an fid or transfer their fid and submit a SignerAdd from the new custody address before the backend has seen the relevant ID registry event
* The backend should still accept SignerAdd messages in this situation

**Comment by varunsrin** [comment]
@varunsrin to spec out all cases, @adityapk00 to implement

**Comment by varunsrin** [comment]
### Cast Ordering

- A CastRemove arrives before the CastAdd
- A CastAdd for a child is seen without the parent CastAdd
- A CastAdd for a child is seen before the parent CastAdd
- A CastAdd for a child is seen after the parent CastAdd received a CastRemove

### Revocations

- A SignerAdd with CastAdds, CastRemoves, ReactionAdds, ReactionRemoves, UserData is removed with a SignerRemove

### Messages arriving before on-chain event

- A UserDataAdd arrives before fid event
- A UserDataAdd for fname arrives before fname event
- A SignerAdd arrives before fid event
- A CastAdd arrives before fid event
- A ReactionAdd arrives before fid event

**Comment by adityapk00** [comment]
Notes for testing:

Message Ordering: For the following tests, the 2nd message is never added to the hub because it fails validation.

- A CastRemove arrives before the CastAdd
  - The CastAdd is never added    
  
- A ReactionRemove arrives before the ReactionAdd
  - The reactionAdd is never added

- A UserDataAdd for time t+1 arrives before a UserDataAdd for time t
  - The 't' UserDataAdd is never added

**Comment by adityapk00** [comment]
Merged into the backend repo.
