### ISSUE TITLE
[farcaster/js] bug: getCastsByFid returns items out of order

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#611]
**What is the bug?**
Items returned by getCastsByFid do not appear in reverse chronological order as expected

**How can it be reproduced? (optional)**

```
const js = require('@farcaster/js');
const client = new js.Client(process.env['HUB_ADDR']);
const result = await client.getCastsByFid(2);
console.log(result._unsafeUnwrap());
```

**Comment by deodad** [comment]
`CastAdd` keys are being [made](https://github.com/farcasterxyz/hubble/blob/main/apps/hubble/src/storage/stores/castStore.ts#L481-L482) with `message.hash`.

Should these keys use `message.tsHash` so that [iterating over them](https://github.com/farcasterxyz/hubble/blob/main/apps/hubble/src/storage/stores/castStore.ts#L148-L150) will give the same order as the messages they reference?

**Comment by varunsrin** [comment]
i'll let @pfletcherhill weigh in on this, but the other way to do this might be to iterate over all cast messages (which are ordered) and just filter out the ones that are also in the add set

**Comment by pfletcherhill** [comment]
If we want all the `get*ByFid` methods to return messages chronologically, then I think Varun's suggestion of iterating over the messages themselves (from a certain store) and applying a filter is the best approach. The adds and removes sets are indexed by hash because that's what clients/users use to reference a cast and we want to keep tsHash as an internal concept. We can adopt a similar approach to the `getAll*MessagesByFid` methods—that's the same method just without applying a filter.

**Comment by varunsrin** [comment]
ok, we're ready to move forward, but i know @pfletcherhill and @deodad have their hands full this week. will flag it with help wanted and share on fc.
